MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

TOWARD_COIN='TOWARD_COIN'
AWAY_COIN='AWAY_COIN'

REPEAT_MOVE='REPEAT_MOVE'
NEW_EXPLORATION='NEW_EXPLORATION'

SUICIDE='SUICIDE'
TRY_TO_SAVE_SELF='TRY_TO_SAVE_SELF'

SUICIDE_BOMB='SUICIDE_BOMB'
NICE_TRY_BOMB='NICE_TRY_BOMB'

NOT_USEFUL_BOMB='NOT_USEFUL_BOMB'
DESTORY_CRATE_LEVEL1='DESTORY_CRATE_LEVEL1'
DESTORY_CRATE_LEVEL2='DESTORY_CRATE_LEVEL2'
TRY_KILL_OTHER='TRY_KILL_OTHER'
SURVIVED_STEP='SURVIVED_STEP'

MOVE_HIGH_POTENTIAL_FIELD='MOVE_HIGH_POTENTIAL_FIELD'
MOVE_LOW_POTENTIAL_FIELD='MOVE_LOW_POTENTIAL_FIELD'

SUCCESS_USE_BOMB='SUCCESS_USE_BOMB'

NOT_EAT_COIN_QUICK='NOT_EAT_COIN_QUICK'

INVALID_BOMB='INVALID_BOMB'

NO_MORE_COIN='NO_MORE_COIN'